### PR TITLE
USC-001-CreateSQLTable

### PR DESCRIPTION
**Pull request by GillonPaterson**
SQL script to make database

### CODE REVIEW

**Review by garethmiskimmin — APPROVED** [review]
is epic table

**Review by nikkalapokojski — CHANGES_REQUESTED** [review]
not null

**Review by garethmiskimmin — APPROVED** [review]
le epic

**Review by garethmiskimmin — APPROVED** [review]
le epic

**Review by nikkalapokojski — APPROVED** [review]
good

**Pull request merged**
